# Generated by Django 5.1.2 on 2024-10-17 10:23

import file_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to=file_manager.models.user_directory_path),
        ),
    ]
