# Generated by Django 5.1.2 on 2024-11-02 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0003_folder_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_files', to='file_manager.folder'),
        ),
    ]
